### ISSUE TITLE
Could you please train the 152-layer model in ImageNet, Then others can use it as a pre-trained model?

### ISSUE THREAD

**Issue by meanmee** [keunwoochoi/residual_block_keras#6]

**Comment by keunwoochoi** [comment]
Sorry but I don't think I could - I'm not working on images and haven't worked with imagenet dataset so far.
If I have an off-the-shelf code like the `example.py` in the repo I would love to try. Not sure it's feasible with my gpu (Tesla X, 12GB memory) though.

**Comment by iamaaditya** [comment]
Here https://github.com/KaimingHe/deep-residual-networks you will find caffe model and pretrained weights. There are several codes online which converts caffe weights and model into Keras.

If you are agnostic to the library, then torch has weights and model uploaded here https://github.com/facebook/fb.resnet.torch
