### ISSUE TITLE
Run time for the RESNET

### ISSUE THREAD

**Issue by prajwal967** [keunwoochoi/residual_block_keras#9]
I ran the RESNET code for 15 epochs on the MNIST dataset, the code took 6 hours : 42 Minutes.
Is there something you could change to reduce the runtime

**Comment by keunwoochoi** [comment]
Hi, you could try to reduce the model size e.g. number of feature maps. ResNet are known to take long time in general.

**Comment by prajwal967** [comment]
Thank You
